name: Atualizar Base de Prospecção

on:
  schedule:
    - cron: '0 0 1 * *' # Roda à meia-noite do dia 1 de cada mês
  workflow_dispatch: # Permite rodar manualmente pelo painel do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install requests polars pandas

      - name: Executar Script ETL
        run: python etl_cnpj.py

      - name: Commit e Push do Banco de Dados
        run: |
          git config --global user.name "Bot de Dados"
          git config --global user.email "bot@github.com"
          git add data/prospeccao.db
          git commit -m "Atualização mensal dos dados da Receita" || exit 0
          git push
